import "./globals.css";
import  "bootstrap/dist/css/bootstrap.min.css"
import AddBootstrap from "./AddBootstrap";
import { Montserrat } from 'next/font/google'

const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata = {
  title: "Jeelaan Healthcare",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
     <html lang="en">
      <body className={montserrat.className}>
        <AddBootstrap/>
        {children}</body>
    </html>
  );
}
